version: '3.4'

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    ports:
      - "80:80"
      - "443:443"
    build:
      context: .
      dockerfile: WebApp/Dockerfile
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data: